spring:
  datasource:
    url: jdbc:mysql://115.190.114.159:3306/openlynxe_db?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Liangzi_12597758
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  ai:
    memory:
      mysql:
        enabled: true
